### ISSUE TITLE
Missing psilotc.mat file?

### ISSUE THREAD

**Issue by singlesp** [decolab/pnas-neuromod#1]
It appears that this file is missing from the GitHub repository.

**Comment by Jiang121** [comment]
How can we obtain this file?

**Comment by gustavodeco** [comment]
Hi! I just uploaded the file, sorry about that :)

**Comment by gustavodeco** [comment]
I am so sorry for the late reply, I just saw this message and uploaded the file

**Comment by Jiang121** [comment]
Thank you very much!


| |
jiang
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/16/2021 17:25，Gustavo ***@***.***> wrote：

I am so sorry for the late reply, I just saw this message and uploaded the file

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by singlesp** [comment]
Thank you Gus :)
